// Defines the which sons and the order in which they are shown in this section.
// Include in pisnicky/default.typ to be shown

#include "eldorado.typ"
#include "frankie_dlouhan.typ"
#include "hudsonsky_sify.typ"
#include "valka_ruzi.typ"
#include "mezi_horami.typ"
#include "jaro.typ"
#include "bedna_od_whisky.typ"
#include "sedmnact_dnu.typ"
#include "tri_krize.typ"
#include "blizko_little_big_hornu.typ"
#include "hrobar.typ"
#include "nad_stadem_koni.typ"
// #include "baroko.typ"
#include "slavici_z_madridu.typ"
#include "tisic_mil.typ"
#include "velicenstvo_kat.typ"
//#include "nebesti_jezdci.typ"
//#include "tereza_osamely_mesto.typ"
#include "morituri_te_salutant.typ"
//#include "country_roads.typ"
#include "to_ta_helpa.typ"
#include "dej_mi_vic_sve_lasky.typ"
#include "cernej_pasazer.typ"
//#include "slapej_dal.typ"
//#include "leden_je_leden.typ"
#include "hejkal.typ"
#include "batalion.typ"
#include "amerika.typ"
//#include "missisippi.typ"
#include "lokomotiva.typ"
#include "andel.typ"
